# Generated by Django 4.0.2 on 2022-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
