# Generated by Django 4.0.2 on 2022-03-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_tag_delete_blog_post_author_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_names',
            new_name='image_name',
        ),
    ]
