# Generated by Django 4.0.2 on 2022-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_image_names_post_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='short_intro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
