# Generated by Django 4.0.2 on 2022-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_job_title_author_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
